 /run/initialize
/vis/open OGL 600x600-0+0

/vis/drawVolume

/vis/scene/add/trajectories smooth

############draw by particle ID############################
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set proton blue
/vis/modeling/trajectories/drawByParticleID-0/set neutron white
###########################################################

#/vis/modeling/trajectories/create/drawByAttribute
#/vis/modeling/trajectories/drawByAttribute-0/setAttribute IMag
#/vis/modeling/trajectories/drawByAttribute-0/addInterval interval1 0.0 MeV 200.0 MeV
#/vis/modeling/trajectories/drawByAttribute-0/addInterval interval2 200.00 MeV 400. MeV
#/vis/modeling/trajectories/drawByAttribute-0/addInterval interval3 400.00 MeV 700. MeV
#/vis/modeling/trajectories/drawByAttribute-0/addInterval interval4 700 MeV 1.00 GeV
#/vis/modeling/trajectories/drawByAttribute-0/addInterval interval5 1.00 GeV 2.00 GeV
#/vis/modeling/trajectories/drawByAttribute-0/addInterval interval6 2.00 GeV 4.00 GeV
#/vis/modeling/trajectories/drawByAttribute-0/addInterval interval7 4.00 GeV 6.00 GeV
#/vis/modeling/trajectories/drawByAttribute-0/addInterval interval8 6.00 GeV 8.00 GeV

#/vis/modeling/trajectories/drawByAttribute-0/interval1/setLineColourRGBA 1. 1. 1. 1       # white
#/vis/modeling/trajectories/drawByAttribute-0/interval2/setLineColourRGBA 0.5 0.5 0.5 1    # gray
#/vis/modeling/trajectories/drawByAttribute-0/interval3/setLineColourRGBA 1. 0. 0. 1       # red
#/vis/modeling/trajectories/drawByAttribute-0/interval4/setLineColourRGBA 0. 1. 0. 1       # green
#/vis/modeling/trajectories/drawByAttribute-0/interval5/setLineColourRGBA 0. 0. 1. 1       # blue
#/vis/modeling/trajectories/drawByAttribute-0/interval6/setLineColourRGBA 1. 0. 1. 1       # magenta
#/vis/modeling/trajectories/drawByAttribute-0/interval6/setLineColourRGBA 1. 1. 0. 1       # yellow

/vis/scene/endOfEventAction accumulate

#################wirefram view################
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100

#################surface view#################
#/vis/viewer/set/style surface




